

services:
  setup:
    build:
      context: setup_image
    profiles:
      - setup

  postgresql:
#    profiles:
#      - disabled
    build:
      context: ${HCS_PG_IMAGE_DIR}
    environment:
      - POSTGRES_PASSWORD=${HCS_PG_PASSWORD}
    user: ${HCS_UID}:${HCS_GID}
    ports:
      - target: 5432
        published: ${HCS_PG_PORT}
        host_ip: ${HCS_PG_HOST}
    volumes:
      - type: bind
        source: ${HCS_PG_CONTAINER_DIR}/data-volume
        target: /var/lib/postgresql/data
#      - type: bind
#        source: /etc/passwd
#        target: /etc/passwd
#        read_only: true
#

  elasticsearch:
    build:
      context: ${HCS_ESREST_IMAGE_DIR}
    environment:
      - discovery.type=single-node
      - xpack.security.enabled=true
      - "ES_JAVA_OPTS=-Xms512m -Xmx512m"
      - bootstrap.memory_lock=true
      - ELASTIC_PASSWORD=changeme
    ulimits:
      memlock:
        soft: -1
        hard: -1
    user: ${HCS_UID}:${HCS_GID}
    ports:
      - target: 9200
        host_ip: ${HCS_ESREST_HOST}
        published: ${HCS_ESREST_PORT}
    volumes:
      - type: bind
        source: ${HCS_ESREST_CONTAINER_DIR}/data-volume
        target: /usr/share/elasticsearch/data

  kibana:
    depends_on:
      - elasticsearch
    build:
      context: ${HCS_KIBANA_IMAGE_DIR}
    environment:
      - ELASTICSEARCH_HOSTS=http://elasticsearch:9200
      - xpack.security.enabled=true
      - ELASTICSEARCH_USERNAME=elastic
      - ELASTICSEARCH_PASSWORD=changeme
    ports:
      - target: 5601
        host_ip: ${HCS_KIBANA_HOST}
        published: ${HCS_KIBANA_PORT}


  opensearch:
    profiles:
      - disabled
    build:
      context: ${HCS_OSREST_IMAGE_DIR}
    environment:
      # https://github.com/opensearch-project/OpenSearch/issues/1598#issuecomment-978189603
      # https://github.com/opensearch-project/opensearch-build/blob/main/docker/release/README.md#scenario-2-no-demo-certsconfigs--disable-security-on-both-opensearch-and-opensearch-dashboards
      - discovery.type=single-node
      - DISABLE_SECURITY_PLUGIN=true
      - DISABLE_INSTALL_DEMO_CONFIG=true
    user: ${HCS_UID}:${HCS_GID}
    ports:
      - target: 9200
        host_ip: ${HCS_OSREST_HOST}
        published: ${HCS_OSREST_PORT}
      - target: 9600
        host_ip: ${OSPERF_HOST}
        published: ${OSPERF_PORT}
    volumes:
      - type: bind
        source: ${HCS_OSREST_CONTAINER_DIR}/data-volume
        target: /usr/share/opensearch/data
#
  opensearch-dashboards:
    profiles:
      - disabled
    depends_on:
      - opensearch
    build:
      context: ${HCS_OSDBS_IMAGE_DIR}
    environment:
      - OPENSEARCH_HOSTS=["http://opensearch:9200"]
      - DISABLE_SECURITY_DASHBOARDS_PLUGIN=true
    ports:
      - target: 5601
        host_ip: ${HCS_OSDBS_HOST}
        published: ${HCS_OSDBS_PORT}
#
  hapi-run:
#    profiles:
#      - disabled
    depends_on:
      - elasticsearch
      - postgresql
    build:
      context: ${HCS_HAPIRUN_IMAGE_DIR}
    environment:
      - HCS_HAPIRUN_JAR
      - HCS_HAPIRUN_JAVA_OPTIONS
      - HCS_HAPIRUN_ARGS
      - HCS_HAPIRUN_CONFIG_LOCATIONS
    ports:
      - target: 8080
        host_ip: ${HCS_HAPIRUN_HOST}
        published: ${HCS_HAPIRUN_PORT}
    user: ${HCS_UID}:${HCS_GID}
    volumes:
      - type: bind
        source: ${HCS_HAPIRUN_CONTAINER_DIR}
        target: /hapi-run
#
